theme: jekyll-theme-slate
github:
  is_project_page: false

plugins:
  - jekyll-seo-tag

title: "Exercise Assets"
tagline: "Welcome to LearningFuze Exercises!"
logo: "/assets/lfz-sm.png"

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/open-graph-image.png"
