version: "3"

services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --incremental --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - /usr/local/bundle
